name: stat_rethinking
channels:
    - defaults
dependencies:
    - jupyterlab
    - seaborn
    - mkl-service
    - graphviz
    - python-graphviz
    - pydot
    - pip
    - pip:
          - watermark
          - arviz
          - pymc3
          - causalgraphicalmodels
          - daft
