name: stat_rethinking
channels:
    - defaults
dependencies:
    - jupyterlab
    - seaborn
    - mkl-service
    - pip
    - pip:
          - watermark
          - "git+git://github.com/arviz-devs/arviz.git@main"
          - "git+git://github.com/pymc-devs/pymc3.git@main"
          - causalgraphicalmodels
          - daft
